# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='number1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
